stages:
  - build

.build-template: &build-definition
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - . ./scripts/version.sh
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - ./scripts/create_docker_image.sh "${CI_REGISTRY_IMAGE}" "${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:minimal--${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:opam--${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - if [ -n "${CI_COMMIT_REF_NAME}" ]; then
        TAG_NAME=$(echo "${CI_COMMIT_REF_NAME}" | tr -c -- '-._\n[:alnum:]' '_') ;
        docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
                   "${CI_REGISTRY_IMAGE}:${TAG_NAME}" ;
        docker push "${CI_REGISTRY_IMAGE}:${TAG_NAME}" ;
      fi

build-safe:
  <<: *build-definition
  only:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository
  tags:
    - safe_docker

build:
  <<: *build-definition
  except:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository
